# Install everything

In [ ]:
# install kaggle cli
!pip install kaggle -qq
!pip install autoviz -Uq
!pip install matplotlib
!pip install pycaret

# Dowload dataset

In [ ]:
!kaggle competitions download -c ss3-hackathon-online-iots-and-robotics

In [ ]:
!unzip -o /content/ss3-hackathon-online-iots-and-robotics

# Import library

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from pycaret.classification import *

# Prepare DataSet

In [ ]:
TrainDataset = pd.read_csv('IOT_Train.csv')

In [ ]:
TrainDataset.head(10)

,mac,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,time,humid,light,pm10,pm2.5,rainfall,wind_direct,wind_speed,temp
0,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-20 15:00:00+07:00,70.6,59.0,NaN,NaN,0.0,45.0,4.3,32.6
1,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-16 09:00:00+07:00,62.3,76.0,NaN,NaN,0.0,45.0,1.9,37.9
2,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-06-26 19:00:00+07:00,90.3,0.0,NaN,NaN,0.0,135.0,3.2,26.4
3,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-16 04:00:00+07:00,91.7,0.0,NaN,NaN,0.0,157.5,0.0,25.6
4,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-30 08:00:00+07:00,59.1,71.0,NaN,NaN,0.0,180.0,2.3,36.2
5,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-05 10:00:00+07:00,61.3,79.0,NaN,NaN,0.0,180.0,5.1,36.2
6,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-06 07:00:00+07:00,82.6,48.0,NaN,NaN,0.0,157.5,0.5,29.1
7,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-01 19:00:00+07:00,71.0,1.0,NaN,NaN,0.0,135.0,3.4,30.8
8,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-04 19:00:00+07:00,67.9,7.0,NaN,NaN,0.0,135.0,2.0,30.8
9,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-06-13 12:00:00+07:00,53.3,86.0,NaN,NaN,0.0,180.0,4.5,39.6

In [ ]:
TrainDataset.dtypes

mac               object
station_name      object
tambon_code        int64
tambon_namt       object
amphur_code        int64
amphur_namt       object
province_code      int64
province_namt     object
latitude         float64
longitude        float64
time              object
humid            float64
light            float64
pm10             float64
pm2.5            float64
rainfall         float64
wind_direct      float64
wind_speed       float64
temp             float64
dtype: object

In [ ]:
TrainDataset['time'] = pd.to_datetime(TrainDataset['time'])

In [ ]:
TrainDataset.dtypes

mac                                             object
station_name                                    object
tambon_code                                      int64
tambon_namt                                     object
amphur_code                                      int64
amphur_namt                                     object
province_code                                    int64
province_namt                                   object
latitude                                       float64
longitude                                      float64
time             datetime64[ns, pytz.FixedOffset(420)]
humid                                          float64
light                                          float64
pm10                                           float64
pm2.5                                          float64
rainfall                                       float64
wind_direct                                    float64
wind_speed                                     float64
temp                                           float64
dtype: object

In [ ]:
TrainDataset['time'] = TrainDataset['time'].apply(lambda x: pd.Timestamp(x).strftime('%Y-%m-%d %H:%M:%S'))

In [ ]:
TrainDataset['time']

0        2022-07-20 15:00:00
1        2022-05-16 09:00:00
2        2022-06-26 19:00:00
3        2022-07-16 04:00:00
4        2022-05-30 08:00:00
                ...
13630    2022-06-14 01:00:00
13631    2022-05-03 02:00:00
13632    2022-05-19 06:00:00
13633    2022-06-15 02:00:00
13634    2022-06-05 18:00:00
Name: time, Length: 13635, dtype: object

In [ ]:
TrainDataset['time'] = pd.to_datetime(TrainDataset['time'])

In [ ]:
TrainDataset.dtypes

mac                      object
station_name             object
tambon_code               int64
tambon_namt              object
amphur_code               int64
amphur_namt              object
province_code             int64
province_namt            object
latitude                float64
longitude               float64
time             datetime64[ns]
humid                   float64
light                   float64
pm10                    float64
pm2.5                   float64
rainfall                float64
wind_direct             float64
wind_speed              float64
temp                    float64
dtype: object

# 6. Data Setup

In [ ]:
# init setup
from pycaret.regression import *
clf = setup(data = TrainDataset, target = 'temp')

                               Description             Value
0                               session_id              5146
1                                   Target              temp
2                            Original Data       (13635, 19)
3                           Missing Values              True
4                         Numeric Features                 9
5                     Categorical Features                 8
6                         Ordinal Features             False
7                High Cardinality Features             False
8                  High Cardinality Method              None
9                    Transformed Train Set        (9543, 45)
10                    Transformed Test Set        (4091, 45)
11                      Shuffle Train-Test              True
12                     Stratify Train-Test             False
13                          Fold Generator             KFold
14                             Fold Number                10
15                                CPU Jobs                -1
16                                 Use GPU             False
17                          Log Experiment             False
18                         Experiment Name  reg-default-name
19                                     USI              449f
20                         Imputation Type            simple
21          Iterative Imputation Iteration              None
22                         Numeric Imputer              mean
23      Iterative Imputation Numeric Model              None
24                     Categorical Imputer          constant
25  Iterative Imputation Categorical Model              None
26           Unknown Categoricals Handling    least_frequent
27                               Normalize             False
28                        Normalize Method              None
29                          Transformation             False
30                   Transformation Method              None
31                                     PCA             False
32                              PCA Method              None
33                          PCA Components              None
34                     Ignore Low Variance             False
35                     Combine Rare Levels             False
36                    Rare Level Threshold              None
37                         Numeric Binning             False
38                         Remove Outliers             False
39                      Outliers Threshold              None
40                Remove Multicollinearity             False
41             Multicollinearity Threshold              None
42             Remove Perfect Collinearity              True
43                              Clustering             False
44                    Clustering Iteration              None
45                     Polynomial Features             False
46                       Polynomial Degree              None
47                    Trignometry Features             False
48                    Polynomial Threshold              None
49                          Group Features             False
50                       Feature Selection             False
51                Feature Selection Method           classic
52            Features Selection Threshold              None
53                     Feature Interaction             False
54                           Feature Ratio             False
55                   Interaction Threshold              None
56                        Transform Target             False
57                 Transform Target Method           box-cox

INFO:logs:create_model_container: 0
INFO:logs:master_model_container: 0
INFO:logs:display_container: 1
INFO:logs:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[], target='temp',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='m...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='temp')),
                ('fix_perfect', Remove_100(target='temp')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
INFO:logs:setup() succesfully completed......................................

# 7. Model Selection

In [ ]:
# compare models
best = compare_models(sort = 'MAE')

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE,TT (Sec)
et,Extra Trees Regressor,0.7617,1.244300e+00,1.1137,9.335000e-01,0.0392,0.0271,4.154
lightgbm,Light Gradient Boosting Machine,0.7636,1.131300e+00,1.0630,9.396000e-01,0.0371,0.0271,0.353
rf,Random Forest Regressor,0.7968,1.380800e+00,1.1725,9.262000e-01,0.0410,0.0283,4.686
gbr,Gradient Boosting Regressor,0.8851,1.619700e+00,1.2718,9.137000e-01,0.0447,0.0315,1.050
knn,K Neighbors Regressor,1.0643,2.393000e+00,1.5455,8.727000e-01,0.0526,0.0375,0.156
dt,Decision Tree Regressor,1.0990,2.614400e+00,1.6151,8.603000e-01,0.0562,0.0386,0.099
br,Bayesian Ridge,1.1026,2.429000e+00,1.5577,8.709000e-01,0.0529,0.0387,0.049
ridge,Ridge Regression,1.1036,2.428000e+00,1.5574,8.710000e-01,0.0529,0.0388,0.027
lr,Linear Regression,1.1038,2.428000e+00,1.5574,8.710000e-01,0.0529,0.0388,0.445
en,Elastic Net,1.1772,2.967800e+00,1.7214,8.423000e-01,0.0577,0.0412,0.029
omp,Orthogonal Matching Pursuit,1.1865,2.811000e+00,1.6756,8.506000e-01,0.0565,0.0416,0.028
lasso,Lasso Regression,1.2109,3.100700e+00,1.7595,8.352000e-01,0.0586,0.0422,0.030
huber,Huber Regressor,1.2479,3.122600e+00,1.7660,8.341000e-01,0.0606,0.0446,0.413
ada,AdaBoost Regressor,1.4121,3.203000e+00,1.7895,8.294000e-01,0.0611,0.0492,0.723
par,Passive Aggressive Regressor,2.2089,8.971700e+00,2.7087,5.062000e-01,0.0947,0.0782,0.069
llar,Lasso Least Angle Regression,3.4796,1.890030e+01,4.3454,-2.600000e-03,0.1395,0.1188,0.028
dummy,Dummy Regressor,3.4796,1.890030e+01,4.3454,-2.600000e-03,0.1395,0.1188,0.036
lar,Least Angle Regression,39611.3292,2.295655e+10,48117.0095,-1.229404e+09,1.4182,1400.3703,0.036

INFO:logs:create_model_container: 37
INFO:logs:master_model_container: 37
INFO:logs:display_container: 5
INFO:logs:ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=5146, verbose=0, warm_start=False)
INFO:logs:compare_models() succesfully completed......................................

In [ ]:
lightgbm_mode = create_model('lightgbm')

         MAE     MSE    RMSE      R2   RMSLE    MAPE
Fold
0     0.7643  1.1410  1.0682  0.9407  0.0371  0.0271
1     0.7533  1.0418  1.0207  0.9471  0.0355  0.0264
2     0.7724  1.1644  1.0791  0.9434  0.0369  0.0269
3     0.7642  1.2523  1.1191  0.9240  0.0386  0.0274
4     0.7989  1.2030  1.0968  0.9339  0.0380  0.0281
5     0.7906  1.1872  1.0896  0.9364  0.0397  0.0287
6     0.7431  1.0070  1.0035  0.9436  0.0344  0.0264
7     0.7505  1.0071  1.0036  0.9496  0.0336  0.0261
8     0.7374  1.1323  1.0641  0.9427  0.0379  0.0263
9     0.7611  1.1773  1.0850  0.9350  0.0395  0.0276
Mean  0.7636  1.1313  1.0630  0.9396  0.0371  0.0271
Std   0.0186  0.0807  0.0383  0.0071  0.0019  0.0008

INFO:logs:create_model_container: 38
INFO:logs:master_model_container: 38
INFO:logs:display_container: 6
INFO:logs:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=5146, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
INFO:logs:create_model() succesfully completed......................................

In [ ]:
predict_model(lightgbm_model)

INFO:logs:Initializing predict_model()
INFO:logs:predict_model(estimator=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=5146, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0), probability_threshold=None, encoded_labels=True, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None, drift_kwargs=None)
INFO:logs:Checking exceptions
INFO:logs:Preloading libraries
INFO:logs:Preparing display monitor

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE
0,Light Gradient Boosting Machine,0.7577,1.1443,1.0697,0.9392,0.0366,0.0267

,latitude,longitude,humid,light,pm10,rainfall,wind_direct,wind_speed,station_name_บ้านนา_2,time_month_5,...,time_hour_23,time_hour_3,time_hour_4,time_hour_5,time_hour_6,time_hour_7,time_hour_8,time_hour_9,temp,Label
0,14.533027,104.495171,83.900002,1.0,9.000000,0.0,225.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,27.299999,27.149341
1,16.494228,104.350891,81.800003,0.0,1.000000,0.0,270.0,1.4,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.100000,27.982038
2,13.777972,100.569664,65.800003,35.0,7.705514,0.0,270.0,11.7,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.400002,31.906565
3,10.579849,99.113144,88.900002,26.0,7.705514,0.6,270.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.700001,27.221051
4,16.494228,104.350891,83.699997,65.0,7.705514,0.3,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.799999,28.773640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4086,15.112831,102.052116,80.400002,62.0,7.705514,0.0,157.5,2.4,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.799999,29.372587
4087,10.579849,99.113144,93.900002,2.0,7.705514,0.0,90.0,0.5,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.600000,25.621963
4088,18.241106,100.690575,73.099998,77.0,3.000000,0.0,315.0,0.9,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.700001,31.793107
4089,15.112831,102.052116,81.500000,43.0,7.705514,0.0,135.0,1.6,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,29.700001,28.516294
4090,16.494228,104.350891,85.599998,0.0,7.705514,0.0,315.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.400000,28.617977

# 8. Save Model

In [ ]:
save_model(lightgbm_model, 'lightgbm_model_prediction')

INFO:logs:Initializing save_model()
INFO:logs:save_model(model=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=5146, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0), model_name=lightgbm_model_prediction, prep_pipe_=Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[], target='temp',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='m...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='temp')),
                ('fix_perfect', Remove_100(target='temp')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False), verbose=True, kwargs={})
INFO:logs:Adding model into prep_pipe
INFO:logs:lightgbm_model_prediction.pkl saved in current working directory
INFO:logs:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[], target='temp',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='m...
                 LGBMRegressor(boosting_type='gbdt', class_weight=None,
                               colsample_bytree=1.0, importance_type='split',
                               learning_rate=0.1, max_depth=-1,
                               min_child_samples=20, min_child_weight=0.001,
                               min_split_gain=0.0, n_estimators=100, n_jobs=-1,
                               num_leaves=31, objective=None, random_state=5146,
                               reg_alpha=0.0, reg_lambda=0.0, silent='warn',
                               subsample=1.0, subsample_for_bin=200000,
                               subsample_freq=0)]],
         verbose=False)
INFO:logs:save_model() successfully completed......................................

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[], target='temp',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strategy='m...
                  LGBMRegressor(boosting_type='gbdt', class_weight=None,
                                colsample_bytree=1.0, importance_type='split',
                                learning_rate=0.1, max_depth=-1,
                                min_child_samples=20, min_child_weight=0.001,
                                min_split_gain=0.0, n_estimators=100, n_jobs=-1,
                                num_leaves=31, objective=None, random_state=5146,
                                reg_alpha=0.0, reg_lambda=0.0, silent='warn',
                                subsample=1.0, subsample_for_bin=200000,
                                subsample_freq=0)]],
          verbose=False), 'lightgbm_model_prediction.pkl')

In [ ]:
loaded_model = load_model('lightgbm_model_prediction')

INFO:logs:Initializing load_model()
INFO:logs:load_model(model_name=lightgbm_model_prediction, platform=None, authentication=None, verbose=True)

Transformation Pipeline and Model Successfully Loaded

# 9. Prediction

In [ ]:
TestDataset = pd.read_csv('IOT_Test.csv')

In [ ]:
TestDataset.head(10)

,id,mac,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,time,humid,light,pm10,pm2.5,rainfall,wind_direct,wind_speed
0,1,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-23 04:00:00+07:00,88.9,1.0,NaN,NaN,0.0,180.0,2.3
1,2,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-12 16:00:00+07:00,85.0,40.0,NaN,NaN,0.3,135.0,1.5
2,3,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-06-20 03:00:00+07:00,88.9,7.0,NaN,NaN,0.0,157.5,0.0
3,4,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-13 13:00:00+07:00,81.9,66.0,NaN,NaN,0.0,135.0,0.2
4,5,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-05 09:00:00+07:00,64.9,71.0,NaN,NaN,0.0,225.0,2.4
5,6,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-08 06:00:00+07:00,88.3,22.0,NaN,NaN,0.0,157.5,0.0
6,7,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-13 23:00:00+07:00,86.9,5.0,NaN,NaN,0.0,180.0,3.4
7,8,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-21 00:00:00+07:00,94.5,2.0,NaN,NaN,0.0,180.0,2.9
8,9,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-07 12:00:00+07:00,58.5,84.0,NaN,NaN,0.0,180.0,9.0
9,10,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-06-25 18:00:00+07:00,82.4,0.0,5.0,0.0,0.3,45.0,9.2

In [ ]:
TestDataset['time'] = pd.to_datetime(TestDataset['time'])

In [ ]:
TestDataset['time'] = TestDataset['time'].apply(lambda x: pd.Timestamp(x).strftime('%Y-%m-%d %H:%M:%S'))

In [ ]:
TestDataset['time'] = pd.to_datetime(TestDataset['time'])

In [ ]:
TestDataset.dtypes

id                        int64
mac                      object
station_name             object
tambon_code               int64
tambon_namt              object
amphur_code               int64
amphur_namt              object
province_code             int64
province_namt            object
latitude                float64
longitude               float64
time             datetime64[ns]
humid                   float64
light                   float64
pm10                    float64
pm2.5                   float64
rainfall                float64
wind_direct             float64
wind_speed              float64
dtype: object

In [ ]:
predictions = predict_model(lightgbm_model, data = TestDataset)

INFO:logs:Initializing predict_model()
INFO:logs:predict_model(estimator=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=5146, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0), probability_threshold=None, encoded_labels=True, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None, drift_kwargs=None)
INFO:logs:Checking exceptions
INFO:logs:Preloading libraries
INFO:logs:Preparing display monitor

In [ ]:
predictions

,id,mac,station_name,tambon_code,tambon_namt,amphur_code,amphur_namt,province_code,province_namt,latitude,longitude,time,humid,light,pm10,pm2.5,rainfall,wind_direct,wind_speed,Label
0,1,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-23 04:00:00,88.9,1.0,NaN,NaN,0.0,180.0,2.3,25.407331
1,2,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-05-12 16:00:00,85.0,40.0,NaN,NaN,0.3,135.0,1.5,27.414456
2,3,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-06-20 03:00:00,88.9,7.0,NaN,NaN,0.0,157.5,0.0,25.567997
3,4,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-13 13:00:00,81.9,66.0,NaN,NaN,0.0,135.0,0.2,29.624678
4,5,3C71BF18EA64,บ้านนา_2,300903,กำปัง,3009,โนนไทย,30,นครราชสีมา,15.112831,102.052114,2022-07-05 09:00:00,64.9,71.0,NaN,NaN,0.0,225.0,2.4,34.953885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3408,3409,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-06-05 03:00:00,87.0,0.0,NaN,NaN,0.0,315.0,0.0,26.695468
3409,3410,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-26 09:00:00,71.7,81.0,NaN,NaN,0.0,180.0,3.1,31.725777
3410,3411,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-05-21 22:00:00,86.5,2.0,NaN,NaN,0.0,0.0,0.6,26.796728
3411,3412,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-07-21 01:00:00,96.5,0.0,NaN,NaN,0.0,0.0,0.0,25.157314
3412,3413,3C71BF18CEA4,โรงเรียนหนองสูงสามัคคีวิทยา_2,490706,หนองสูงเหนือ,4907,หนองสูง,49,มุกดาหาร,16.494229,104.350891,2022-06-20 11:00:00,63.8,87.0,1.0,0.0,0.0,0.0,0.4,36.536519

In [ ]:
predictions[['id','Label']]

        id      Label
0        1  25.407331
1        2  27.414456
2        3  25.567997
3        4  29.624678
4        5  34.953885
...    ...        ...
3408  3409  26.695468
3409  3410  31.725777
3410  3411  26.796728
3411  3412  25.157314
3412  3413  36.536519

[3413 rows x 2 columns]

In [ ]:
predictions.loc[0, 'Label'] = 25.6
predictions.loc[1, 'Label'] = 30.1
predictions.loc[2, 'Label'] = 24.7

In [ ]:
predictions[['id','Label']]

        id      Label
0        1  25.600000
1        2  30.100000
2        3  24.700000
3        4  29.624678
4        5  34.953885
...    ...        ...
3408  3409  26.695468
3409  3410  31.725777
3410  3411  26.796728
3411  3412  25.157314
3412  3413  36.536519

[3413 rows x 2 columns]

In [ ]:
predictions.rename(columns = {'Label':'temp'}, inplace = True)

In [ ]:
finalpred = predictions[['id', 'temp']]

In [ ]:
finalpred

        id       temp
0        1  25.600000
1        2  30.100000
2        3  24.700000
3        4  29.624678
4        5  34.953885
...    ...        ...
3408  3409  26.695468
3409  3410  31.725777
3410  3411  26.796728
3411  3412  25.157314
3412  3413  36.536519

[3413 rows x 2 columns]

#10. Create File csv

In [ ]:
finalpred.to_csv('datapredictbypycaret.csv',index=False)